version: '3.8'

services:
  digital-hustlas:
    build: .
    ports:
      - "3000:3000"  # Веб-приложение
      - "3001:3001"  # API сервер
    volumes:
      - /home/ubuntu/ProdBy/database.db:/app/database.db
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_PATH=/app/database.db
      - ALLOWED_ORIGINS=http://localhost:3000,https://yourdomain.com
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Опционально: Nginx для reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - digital-hustlas
    restart: unless-stopped
    profiles:
      - nginx
